run cacheLocations: startnode = looongcat.pp.ua:32348
interval set to : 1600 s.
listening on port 8081
 getAllpeers size: 5353
getAllpeers: 55601.902ms
 get all peers location 
empty[-]0
getLocation: 12553.330ms
 start get master nodes 
 get master nodes 
get master nodes: 90161.251ms
--== run locations ==--
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5353
getAllpeers: 55573.199ms
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
 get all peers location 
empty[-]49
getLocation: 23534.234ms
 start get master nodes 
 get master nodes 
get master nodes: 23512.754ms
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5352
getAllpeers: 122354.531ms
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
 get all peers location 
empty[-]83
getLocation: 23580.389ms
 start get master nodes 
 get master nodes 
get master nodes: 80979.077ms
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5352
getAllpeers: 57685.717ms
 get all peers location 
empty[-]0
getLocation: 12728.785ms
 start get master nodes 
 get master nodes 
get master nodes: 49708.345ms
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5352
getAllpeers: 55585.360ms
 get all peers location 
empty[-]0
getLocation: 14227.090ms
 start get master nodes 
 get master nodes 
get master nodes: 23574.649ms
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5353
getAllpeers: 55602.282ms
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
 get all peers location 
empty[-]1
getLocation: 22858.206ms
 start get master nodes 
 get master nodes 
get master nodes: 24007.724ms
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5351
getAllpeers: 55633.039ms
 get all peers location 
empty[-]0
getLocation: 11966.550ms
 start get master nodes 
 get master nodes 
get master nodes: 23787.449ms
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5306
getAllpeers: 57943.765ms
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
 get all peers location 
empty[-]107
getLocation: 23759.901ms
 start get master nodes 
 get master nodes 
get master nodes: 23765.822ms
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5335
getAllpeers: 70666.488ms
 get all peers location 
empty[-]0
getLocation: 13260.391ms
 start get master nodes 
 get master nodes 
get master nodes: 101556.358ms
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5352
getAllpeers: 57926.810ms
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
 get all peers location 
empty[-]5
getLocation: 23666.839ms
 start get master nodes 
 get master nodes 
get master nodes: 23808.779ms
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5353
getAllpeers: 55611.133ms
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
 get all peers location 
empty[-]18
getLocation: 23592.037ms
 start get master nodes 
 get master nodes 
get master nodes: 23744.083ms
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5350
getAllpeers: 59883.396ms
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
 get all peers location 
empty[-]16
getLocation: 23606.579ms
 start get master nodes 
 get master nodes 
get master nodes: 23800.466ms
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5348
getAllpeers: 55593.531ms
 get all peers location 
empty[-]0
getLocation: 12188.389ms
 start get master nodes 
 get master nodes 
get master nodes: 51732.424ms
run cacheLocations: startnode = looongcat.pp.ua:32348
 getAllpeers size: 5348
getAllpeers: 66224.080ms
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
Can't get location  url: looongcat.pp.ua:8080 connect ETIMEDOUT 51.15.82.38:8080
 get all peers location 
empty[-]6
getLocation: 23634.867ms
 start get master nodes 
 get master nodes 
get master nodes: 229681.041ms
